version: '2'
services:
  postgres:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ecommerce
    volumes:
      - ./docker/pgadmin/shared:/shared
    ports:
      - 5433:5432
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=info@user.it
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ./docker/pgadmin/shared/:/shared
    depends_on:
      - postgres
    ports:
      - 5050:80
    networks:
      - default

  rabbit:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672
    hostname: ecommerce-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - default    
    
networks:
  default:
    driver: bridge
